entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"
    
certificatesResolvers:
  myresolver:
    acme:
      email: ssl@rillo5000.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG
